"""龙痕竞技场 WebSocket 消息 ID、协议名和业务名映射。"""

from __future__ import annotations

from harvest_fief import (
    HEARTBEAT_MESSAGE_ID,
    HEARTBEAT_RET_MESSAGE_ID,
    LOGIN_FAIL_MESSAGE_ID,
    LOGIN_MESSAGE_ID,
    LOGIN_REUNIQUE_MESSAGE_ID,
    PACK_PASSWORD_MESSAGE_ID,
    STORAGE_ITEM_CHANGE_MESSAGE_ID,
)


LOGIN_OK_MESSAGE_ID = 10012
KICKOUT_MESSAGE_ID = 10030
GAME_DATA_MESSAGE_ID = 10490

# 骑士比武（普通竞技场 Arena_*）
ARENA_INFO_MESSAGE_ID = 19800
ARENA_HISTORY_MESSAGE_ID = 19802
ARENA_SET_DEFEND_TEAM_MESSAGE_ID = 19804
ARENA_SET_ATTACK_TEAM_MESSAGE_ID = 19806
ARENA_REFRESH_OPPONENTS_MESSAGE_ID = 19808
ARENA_CHALLENGE_MESSAGE_ID = 19810
ARENA_ADD_HISTORY_MESSAGE_ID = 19812
ARENA_GET_DAILY_REWARD_MESSAGE_ID = 19814
ARENA_GET_OPPONENT_TEAM_MESSAGE_ID = 19816
ARENA_CHALLENGE_RESULT_MESSAGE_ID = 19818
ARENA_ADD_LOG_MESSAGE_ID = 19820
ARENA_GET_CHALL_REWARD_MESSAGE_ID = 19822
ARENA_CHANGED_SCORE_MESSAGE_ID = 19824

# 龙痕竞技场（Scararena_*）
SCARARENA_INFO_MESSAGE_ID = 21100
SCARARENA_MATCH_MESSAGE_ID = 21102
SCARARENA_CHALLENGE_MESSAGE_ID = 21104
SCARARENA_CHALLENGE_RESULT_MESSAGE_ID = 21106
SCARARENA_WIN_CHOICE_MESSAGE_ID = 21108
SCARARENA_GET_DAILY_REWARD_MESSAGE_ID = 21110

BATTLE_INFO_MESSAGE_ID = 18002
BATTLE_UNIT_INFO_MESSAGE_ID = 18004
BATTLE_OFFLINE_MESSAGE_ID = 18006
BATTLE_C2S_START_MESSAGE_ID = 18010
BATTLE_S2C_START_MESSAGE_ID = 18012
BATTLE_S2C_END_MESSAGE_ID = 18090
BATTLE_C2S_SET_TIMESCALE_MESSAGE_ID = 18100
BATTLE_S2C_SET_TIMESCALE_MESSAGE_ID = 18102
BATTLE_C2S_AUTO_UNIQUE_SKILL_MESSAGE_ID = 18110
BATTLE_S2C_AUTO_UNIQUE_SKILL_MESSAGE_ID = 18112
BATTLE_C2S_AUTO_ARTIFACT_SKILL_MESSAGE_ID = 18114
BATTLE_S2C_AUTO_ARTIFACT_SKILL_MESSAGE_ID = 18116
BATTLE_S2C_FRAME_BROADCAST_MESSAGE_ID = 18500
BATTLE_S2C_FRAME_HASH_VERIFY_MESSAGE_ID = 18502
BATTLE_C2S_FRAME_HASH_VERIFY_RET_MESSAGE_ID = 18504

# 地图/战斗后的事件状态机。客户端 EventModule 在道具展示或对话结束后以
# Event_func_next 确认当前动作，服务端随后才释放对应地图地标。
EVENT_START_MESSAGE_ID = 13300
EVENT_OPTION_MESSAGE_ID = 13305
EVENT_OPTION_FAILED_MESSAGE_ID = 13310
EVENT_END_MESSAGE_ID = 13315
EVENT_FUNC_ACTION_MESSAGE_ID = 13320
EVENT_FUNC_NEXT_MESSAGE_ID = 13325

# 墓穴 / 罪者深渊（Grave_*）
GRAVE_CHALLENGE_START_MESSAGE_ID = 19400
GRAVE_UNLOCK_NOTIFY_MESSAGE_ID = 19402
GRAVE_PASS_NOTIFY_MESSAGE_ID = 19410
GRAVE_QUICK_BATTLE_MESSAGE_ID = 19414
GRAVE_PHASE_REWARD_PICK_MESSAGE_ID = 19416
GRAVE_ACTIVITY_BUFF_SELECT_MESSAGE_ID = 19418
GRAVE_ACTIVITY_SYNC_MESSAGE_ID = 19420
GRAVE_ACTIVITY_ACTIVE_REWARD_PICK_MESSAGE_ID = 19422
GRAVE_ACTIVITY_ACTIVE_INFO_MESSAGE_ID = 19424
ACTIVITY_GRAVE_INFO_MESSAGE_ID = 12520

# 宫廷棋（Monopoly_*）
MONOPOLY_INFO_MESSAGE_ID = 22300
MONOPOLY_ROLLDICE_MESSAGE_ID = 22302
MONOPOLY_TRIGGER_EVENT_MESSAGE_ID = 22310
MONOPOLY_MOVE_MESSAGE_ID = 22314


MESSAGE_NAMES = {
    LOGIN_MESSAGE_ID: "Login",
    LOGIN_OK_MESSAGE_ID: "Login_ok",
    LOGIN_FAIL_MESSAGE_ID: "Login_fail",
    LOGIN_REUNIQUE_MESSAGE_ID: "Login_reunique",
    KICKOUT_MESSAGE_ID: "Kickout",
    HEARTBEAT_MESSAGE_ID: "Heartbeat",
    HEARTBEAT_RET_MESSAGE_ID: "Heartbeat_ret",
    PACK_PASSWORD_MESSAGE_ID: "Pack_password",
    GAME_DATA_MESSAGE_ID: "Game_data",
    STORAGE_ITEM_CHANGE_MESSAGE_ID: "Storage_notify_itemchange",
    ARENA_INFO_MESSAGE_ID: "Arena_info",
    ARENA_HISTORY_MESSAGE_ID: "Arena_history",
    ARENA_SET_DEFEND_TEAM_MESSAGE_ID: "Arena_set_defendteam",
    ARENA_SET_ATTACK_TEAM_MESSAGE_ID: "Arena_set_attackteam",
    ARENA_REFRESH_OPPONENTS_MESSAGE_ID: "Arena_refresh_opponents",
    ARENA_CHALLENGE_MESSAGE_ID: "Arena_challenge",
    ARENA_ADD_HISTORY_MESSAGE_ID: "Arena_add_history",
    ARENA_GET_DAILY_REWARD_MESSAGE_ID: "Arena_get_dailyreward",
    ARENA_GET_OPPONENT_TEAM_MESSAGE_ID: "Arena_get_opponentteam",
    ARENA_CHALLENGE_RESULT_MESSAGE_ID: "Arena_challenge_result",
    ARENA_ADD_LOG_MESSAGE_ID: "Arena_add_log",
    ARENA_GET_CHALL_REWARD_MESSAGE_ID: "Arena_get_challreward",
    ARENA_CHANGED_SCORE_MESSAGE_ID: "Arena_changed_score",
    SCARARENA_INFO_MESSAGE_ID: "Scararena_info",
    SCARARENA_MATCH_MESSAGE_ID: "Scararena_match",
    SCARARENA_CHALLENGE_MESSAGE_ID: "Scararena_challenge",
    SCARARENA_CHALLENGE_RESULT_MESSAGE_ID: "Scararena_challenge_result",
    SCARARENA_WIN_CHOICE_MESSAGE_ID: "Scararena_winchoice",
    SCARARENA_GET_DAILY_REWARD_MESSAGE_ID: "Scararena_get_dailyreward",
    BATTLE_INFO_MESSAGE_ID: "Battle_info",
    BATTLE_UNIT_INFO_MESSAGE_ID: "Battle_unitinfo",
    BATTLE_OFFLINE_MESSAGE_ID: "Battle_offline",
    BATTLE_C2S_START_MESSAGE_ID: "Battle_C2S_start",
    BATTLE_S2C_START_MESSAGE_ID: "Battle_S2C_start",
    BATTLE_S2C_END_MESSAGE_ID: "Battle_S2C_end",
    BATTLE_C2S_SET_TIMESCALE_MESSAGE_ID: "Battle_C2S_setTimescale",
    BATTLE_S2C_SET_TIMESCALE_MESSAGE_ID: "Battle_S2C_setTimescale",
    BATTLE_C2S_AUTO_UNIQUE_SKILL_MESSAGE_ID: "Battle_C2S_auto_unique_skill",
    BATTLE_S2C_AUTO_UNIQUE_SKILL_MESSAGE_ID: "Battle_S2C_auto_unique_skill",
    BATTLE_C2S_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "Battle_C2S_auto_artifact_skill",
    BATTLE_S2C_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "Battle_S2C_auto_artifact_skill",
    BATTLE_S2C_FRAME_BROADCAST_MESSAGE_ID: "Battle_S2C_frame_broadcast",
    BATTLE_S2C_FRAME_HASH_VERIFY_MESSAGE_ID: "Battle_S2C_frame_hash_verify",
    BATTLE_C2S_FRAME_HASH_VERIFY_RET_MESSAGE_ID: "Battle_C2S_frame_hash_verify_ret",
    EVENT_START_MESSAGE_ID: "Event_start",
    EVENT_OPTION_MESSAGE_ID: "Event_option",
    EVENT_OPTION_FAILED_MESSAGE_ID: "Event_option_failed",
    EVENT_END_MESSAGE_ID: "Event_end",
    EVENT_FUNC_ACTION_MESSAGE_ID: "Event_func_action",
    EVENT_FUNC_NEXT_MESSAGE_ID: "Event_func_next",
    GRAVE_CHALLENGE_START_MESSAGE_ID: "Grave_chanllenge_start",
    GRAVE_UNLOCK_NOTIFY_MESSAGE_ID: "Grave_unlock_notify",
    GRAVE_PASS_NOTIFY_MESSAGE_ID: "Grave_pass_notify",
    GRAVE_QUICK_BATTLE_MESSAGE_ID: "Grave_quick_battle",
    GRAVE_PHASE_REWARD_PICK_MESSAGE_ID: "Grave_phase_reward_pick",
    GRAVE_ACTIVITY_BUFF_SELECT_MESSAGE_ID: "Grave_activity_buff_select",
    GRAVE_ACTIVITY_SYNC_MESSAGE_ID: "Grave_activity_sync",
    GRAVE_ACTIVITY_ACTIVE_REWARD_PICK_MESSAGE_ID: "Grave_activity_active_reward_pick",
    GRAVE_ACTIVITY_ACTIVE_INFO_MESSAGE_ID: "Grave_activity_active_info",
    ACTIVITY_GRAVE_INFO_MESSAGE_ID: "Activity_grave_info",
    MONOPOLY_INFO_MESSAGE_ID: "Monopoly_info",
    MONOPOLY_ROLLDICE_MESSAGE_ID: "Monopoly_rolldice",
    MONOPOLY_TRIGGER_EVENT_MESSAGE_ID: "Monopoly_triggerevent",
    MONOPOLY_MOVE_MESSAGE_ID: "Monopoly_move",
}


WEBSOCKET_BUSINESS_NAMES = {
    LOGIN_MESSAGE_ID: "开始登录",
    LOGIN_OK_MESSAGE_ID: "登录成功",
    LOGIN_FAIL_MESSAGE_ID: "登录失败",
    LOGIN_REUNIQUE_MESSAGE_ID: "登录完成",
    KICKOUT_MESSAGE_ID: "登录会话中止",
    HEARTBEAT_MESSAGE_ID: "接收心跳",
    HEARTBEAT_RET_MESSAGE_ID: "返回心跳",
    PACK_PASSWORD_MESSAGE_ID: "获取会话密码",
    GAME_DATA_MESSAGE_ID: "同步游戏数据",
    STORAGE_ITEM_CHANGE_MESSAGE_ID: "同步物品变动",
    ARENA_INFO_MESSAGE_ID: "查询骑士比武",
    ARENA_HISTORY_MESSAGE_ID: "查询骑士比武历史",
    ARENA_SET_DEFEND_TEAM_MESSAGE_ID: "设置骑士比武防守阵容",
    ARENA_SET_ATTACK_TEAM_MESSAGE_ID: "设置骑士比武进攻阵容",
    ARENA_REFRESH_OPPONENTS_MESSAGE_ID: "刷新骑士比武对手",
    ARENA_CHALLENGE_MESSAGE_ID: "挑战骑士比武对手",
    ARENA_ADD_HISTORY_MESSAGE_ID: "追加骑士比武历史",
    ARENA_GET_DAILY_REWARD_MESSAGE_ID: "领取骑士比武每日奖励",
    ARENA_GET_OPPONENT_TEAM_MESSAGE_ID: "查询骑士比武对手阵容",
    ARENA_CHALLENGE_RESULT_MESSAGE_ID: "骑士比武挑战结算",
    ARENA_ADD_LOG_MESSAGE_ID: "追加骑士比武战报",
    ARENA_GET_CHALL_REWARD_MESSAGE_ID: "领取骑士比武挑战次数奖励",
    ARENA_CHANGED_SCORE_MESSAGE_ID: "骑士比武积分变更",
    SCARARENA_INFO_MESSAGE_ID: "查询竞技场",
    SCARARENA_MATCH_MESSAGE_ID: "请求刷新对手",
    SCARARENA_CHALLENGE_MESSAGE_ID: "挑战竞技场对手",
    SCARARENA_CHALLENGE_RESULT_MESSAGE_ID: "竞技场挑战结算",
    SCARARENA_WIN_CHOICE_MESSAGE_ID: "竞技场胜利抉择",
    SCARARENA_GET_DAILY_REWARD_MESSAGE_ID: "领取竞技场每日奖励",
    BATTLE_INFO_MESSAGE_ID: "获取战斗信息",
    BATTLE_UNIT_INFO_MESSAGE_ID: "同步战斗单位",
    BATTLE_OFFLINE_MESSAGE_ID: "战斗离线通知",
    BATTLE_C2S_START_MESSAGE_ID: "请求开始战斗",
    BATTLE_S2C_START_MESSAGE_ID: "战斗开始",
    BATTLE_S2C_END_MESSAGE_ID: "战斗结束",
    BATTLE_C2S_SET_TIMESCALE_MESSAGE_ID: "设置战斗速度",
    BATTLE_S2C_SET_TIMESCALE_MESSAGE_ID: "确认战斗速度",
    BATTLE_C2S_AUTO_UNIQUE_SKILL_MESSAGE_ID: "设置自动角色技能",
    BATTLE_S2C_AUTO_UNIQUE_SKILL_MESSAGE_ID: "确认自动角色技能",
    BATTLE_C2S_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "设置自动圣物技能",
    BATTLE_S2C_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "确认自动圣物技能",
    BATTLE_S2C_FRAME_BROADCAST_MESSAGE_ID: "同步战斗帧",
    BATTLE_S2C_FRAME_HASH_VERIFY_MESSAGE_ID: "校验战斗帧",
    BATTLE_C2S_FRAME_HASH_VERIFY_RET_MESSAGE_ID: "返回战斗帧校验",
    EVENT_START_MESSAGE_ID: "开始地图事件",
    EVENT_OPTION_MESSAGE_ID: "提交地图事件选项",
    EVENT_OPTION_FAILED_MESSAGE_ID: "地图事件选项失败",
    EVENT_END_MESSAGE_ID: "地图事件结束",
    EVENT_FUNC_ACTION_MESSAGE_ID: "地图事件展示/等待动作",
    EVENT_FUNC_NEXT_MESSAGE_ID: "确认地图事件展示/等待动作",
    GRAVE_CHALLENGE_START_MESSAGE_ID: "开始罪者深渊/墓穴挑战",
    GRAVE_UNLOCK_NOTIFY_MESSAGE_ID: "墓穴解锁通知",
    GRAVE_PASS_NOTIFY_MESSAGE_ID: "墓穴通关通知",
    GRAVE_QUICK_BATTLE_MESSAGE_ID: "墓穴快速战斗",
    GRAVE_PHASE_REWARD_PICK_MESSAGE_ID: "领取墓穴阶段奖励",
    GRAVE_ACTIVITY_BUFF_SELECT_MESSAGE_ID: "选择罪者深渊增益",
    GRAVE_ACTIVITY_SYNC_MESSAGE_ID: "同步罪者深渊状态",
    GRAVE_ACTIVITY_ACTIVE_REWARD_PICK_MESSAGE_ID: "领取罪者深渊活跃奖励",
    GRAVE_ACTIVITY_ACTIVE_INFO_MESSAGE_ID: "查询罪者深渊活跃信息",
    ACTIVITY_GRAVE_INFO_MESSAGE_ID: "活动罪者深渊信息",
    MONOPOLY_INFO_MESSAGE_ID: "查询宫廷棋状态",
    MONOPOLY_ROLLDICE_MESSAGE_ID: "宫廷棋掷骰",
    MONOPOLY_TRIGGER_EVENT_MESSAGE_ID: "触发宫廷棋事件",
    MONOPOLY_MOVE_MESSAGE_ID: "宫廷棋移动",
}


def message_name(message_id: int) -> str | None:
    """返回协议消息名；未登记时返回 ``None``。"""

    return MESSAGE_NAMES.get(message_id)


def business_name(message_id: int) -> str | None:
    """返回固定业务名；未登记时返回 ``None``。"""

    return WEBSOCKET_BUSINESS_NAMES.get(message_id)
