"""龙痕竞技场 WebSocket 消息 ID、协议名和业务名映射。"""

from __future__ import annotations

from harvest_fief import (
    HEARTBEAT_MESSAGE_ID,
    HEARTBEAT_RET_MESSAGE_ID,
    LOGIN_FAIL_MESSAGE_ID,
    LOGIN_MESSAGE_ID,
    LOGIN_REUNIQUE_MESSAGE_ID,
    PACK_PASSWORD_MESSAGE_ID,
    STORAGE_ITEM_CHANGE_MESSAGE_ID,
)


LOGIN_OK_MESSAGE_ID = 10012
KICKOUT_MESSAGE_ID = 10030
GAME_DATA_MESSAGE_ID = 10490

SCARARENA_INFO_MESSAGE_ID = 21100
SCARARENA_MATCH_MESSAGE_ID = 21102
SCARARENA_CHALLENGE_MESSAGE_ID = 21104
SCARARENA_CHALLENGE_RESULT_MESSAGE_ID = 21106
SCARARENA_WIN_CHOICE_MESSAGE_ID = 21108
SCARARENA_GET_DAILY_REWARD_MESSAGE_ID = 21110

BATTLE_INFO_MESSAGE_ID = 18002
BATTLE_UNIT_INFO_MESSAGE_ID = 18004
BATTLE_OFFLINE_MESSAGE_ID = 18006
BATTLE_C2S_START_MESSAGE_ID = 18010
BATTLE_S2C_START_MESSAGE_ID = 18012
BATTLE_S2C_END_MESSAGE_ID = 18090
BATTLE_C2S_SET_TIMESCALE_MESSAGE_ID = 18100
BATTLE_S2C_SET_TIMESCALE_MESSAGE_ID = 18102
BATTLE_C2S_AUTO_UNIQUE_SKILL_MESSAGE_ID = 18110
BATTLE_S2C_AUTO_UNIQUE_SKILL_MESSAGE_ID = 18112
BATTLE_C2S_AUTO_ARTIFACT_SKILL_MESSAGE_ID = 18114
BATTLE_S2C_AUTO_ARTIFACT_SKILL_MESSAGE_ID = 18116
BATTLE_S2C_FRAME_BROADCAST_MESSAGE_ID = 18500
BATTLE_S2C_FRAME_HASH_VERIFY_MESSAGE_ID = 18502
BATTLE_C2S_FRAME_HASH_VERIFY_RET_MESSAGE_ID = 18504


MESSAGE_NAMES = {
    LOGIN_MESSAGE_ID: "Login",
    LOGIN_OK_MESSAGE_ID: "Login_ok",
    LOGIN_FAIL_MESSAGE_ID: "Login_fail",
    LOGIN_REUNIQUE_MESSAGE_ID: "Login_reunique",
    KICKOUT_MESSAGE_ID: "Kickout",
    HEARTBEAT_MESSAGE_ID: "Heartbeat",
    HEARTBEAT_RET_MESSAGE_ID: "Heartbeat_ret",
    PACK_PASSWORD_MESSAGE_ID: "Pack_password",
    GAME_DATA_MESSAGE_ID: "Game_data",
    STORAGE_ITEM_CHANGE_MESSAGE_ID: "Storage_notify_itemchange",
    SCARARENA_INFO_MESSAGE_ID: "Scararena_info",
    SCARARENA_MATCH_MESSAGE_ID: "Scararena_match",
    SCARARENA_CHALLENGE_MESSAGE_ID: "Scararena_challenge",
    SCARARENA_CHALLENGE_RESULT_MESSAGE_ID: "Scararena_challenge_result",
    SCARARENA_WIN_CHOICE_MESSAGE_ID: "Scararena_winchoice",
    SCARARENA_GET_DAILY_REWARD_MESSAGE_ID: "Scararena_get_dailyreward",
    BATTLE_INFO_MESSAGE_ID: "Battle_info",
    BATTLE_UNIT_INFO_MESSAGE_ID: "Battle_unitinfo",
    BATTLE_OFFLINE_MESSAGE_ID: "Battle_offline",
    BATTLE_C2S_START_MESSAGE_ID: "Battle_C2S_start",
    BATTLE_S2C_START_MESSAGE_ID: "Battle_S2C_start",
    BATTLE_S2C_END_MESSAGE_ID: "Battle_S2C_end",
    BATTLE_C2S_SET_TIMESCALE_MESSAGE_ID: "Battle_C2S_setTimescale",
    BATTLE_S2C_SET_TIMESCALE_MESSAGE_ID: "Battle_S2C_setTimescale",
    BATTLE_C2S_AUTO_UNIQUE_SKILL_MESSAGE_ID: "Battle_C2S_auto_unique_skill",
    BATTLE_S2C_AUTO_UNIQUE_SKILL_MESSAGE_ID: "Battle_S2C_auto_unique_skill",
    BATTLE_C2S_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "Battle_C2S_auto_artifact_skill",
    BATTLE_S2C_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "Battle_S2C_auto_artifact_skill",
    BATTLE_S2C_FRAME_BROADCAST_MESSAGE_ID: "Battle_S2C_frame_broadcast",
    BATTLE_S2C_FRAME_HASH_VERIFY_MESSAGE_ID: "Battle_S2C_frame_hash_verify",
    BATTLE_C2S_FRAME_HASH_VERIFY_RET_MESSAGE_ID: "Battle_C2S_frame_hash_verify_ret",
}


WEBSOCKET_BUSINESS_NAMES = {
    LOGIN_MESSAGE_ID: "开始登录",
    LOGIN_OK_MESSAGE_ID: "登录成功",
    LOGIN_FAIL_MESSAGE_ID: "登录失败",
    LOGIN_REUNIQUE_MESSAGE_ID: "登录完成",
    KICKOUT_MESSAGE_ID: "登录会话中止",
    HEARTBEAT_MESSAGE_ID: "接收心跳",
    HEARTBEAT_RET_MESSAGE_ID: "返回心跳",
    PACK_PASSWORD_MESSAGE_ID: "获取会话密码",
    GAME_DATA_MESSAGE_ID: "同步游戏数据",
    STORAGE_ITEM_CHANGE_MESSAGE_ID: "同步物品变动",
    SCARARENA_INFO_MESSAGE_ID: "查询竞技场",
    SCARARENA_MATCH_MESSAGE_ID: "请求刷新对手",
    SCARARENA_CHALLENGE_MESSAGE_ID: "挑战竞技场对手",
    SCARARENA_CHALLENGE_RESULT_MESSAGE_ID: "竞技场挑战结算",
    SCARARENA_WIN_CHOICE_MESSAGE_ID: "竞技场胜利抉择",
    SCARARENA_GET_DAILY_REWARD_MESSAGE_ID: "领取竞技场每日奖励",
    BATTLE_INFO_MESSAGE_ID: "获取战斗信息",
    BATTLE_UNIT_INFO_MESSAGE_ID: "同步战斗单位",
    BATTLE_OFFLINE_MESSAGE_ID: "战斗离线通知",
    BATTLE_C2S_START_MESSAGE_ID: "请求开始战斗",
    BATTLE_S2C_START_MESSAGE_ID: "战斗开始",
    BATTLE_S2C_END_MESSAGE_ID: "战斗结束",
    BATTLE_C2S_SET_TIMESCALE_MESSAGE_ID: "设置战斗速度",
    BATTLE_S2C_SET_TIMESCALE_MESSAGE_ID: "确认战斗速度",
    BATTLE_C2S_AUTO_UNIQUE_SKILL_MESSAGE_ID: "设置自动角色技能",
    BATTLE_S2C_AUTO_UNIQUE_SKILL_MESSAGE_ID: "确认自动角色技能",
    BATTLE_C2S_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "设置自动圣物技能",
    BATTLE_S2C_AUTO_ARTIFACT_SKILL_MESSAGE_ID: "确认自动圣物技能",
    BATTLE_S2C_FRAME_BROADCAST_MESSAGE_ID: "同步战斗帧",
    BATTLE_S2C_FRAME_HASH_VERIFY_MESSAGE_ID: "校验战斗帧",
    BATTLE_C2S_FRAME_HASH_VERIFY_RET_MESSAGE_ID: "返回战斗帧校验",
}


def message_name(message_id: int) -> str | None:
    """返回协议消息名；未登记时返回 ``None``。"""

    return MESSAGE_NAMES.get(message_id)


def business_name(message_id: int) -> str | None:
    """返回固定业务名；未登记时返回 ``None``。"""

    return WEBSOCKET_BUSINESS_NAMES.get(message_id)
