export const __webpack_id__ = 12638; export const __webpack_ids__ = [12638]; export const __webpack_modules__ = {
    51729: (i, t, e) => {
        e.r(t), e.d(t, { SigninPanel1: () => SigninPanel1 }); var n = e(15662), s = e(30783), a = e(36976), o = e(58403), r = e(52936), d = e(23307), c = e(22370), h = e(34926), l = e(51072), g = e(77095), f = e(26136), I = e(88244), u = e(95569), __decorate = function (i, t, e, n) { var s, a = arguments.length, o = a < 3 ? t : null === n ? n = Object.getOwnPropertyDescriptor(t, e) : n; if ("object" == typeof Reflect && "function" == typeof Reflect.decorate) o = Reflect.decorate(i, t, e, n); else for (var r = i.length - 1; r >= 0; r--)(s = i[r]) && (o = (a < 3 ? s(o) : a > 3 ? s(t, e, o) : s(t, e)) || o); return a > 3 && o && Object.defineProperty(t, e, o), o }, __metadata = function (i, t) { if ("object" == typeof Reflect && "function" == typeof Reflect.metadata) return Reflect.metadata(i, t) }; class SigninPanel1 extends s.Z {
            constructor() { super(...arguments), this.prefabPath = "Assets/Art/Prefabs/UI/activity/boxDaily7.prefab", this.group = a.Y.High, this.isPopup = !0, this.signinId = 0, this.dbRow = null, this.dbRewards = [] } async onShow(i) { console.log("SigninPanel"), this.signinId = i && i.activityId ? i.activityId : l.aR.DailySignin_Channel, await this.initData(), await this.refreshUI(), r.GuideManager.instance.forcePause() } onRegMsg() { this.on("activity_signin_suc", this.onSigninSuc.bind(this)) } async initData() { this.signinData = gameData().activity.getSigninDataById(this.signinId), this.dbRow = gameData().activity.getSigninDesignData(this.signinId), this.dbRewards = []; let i = this.dbRow.rewards.split("#"); for (let t of i) { let i = t.split(",").map(Number), e = i.length >= 4 ? i[3] : 0; this.dbRewards.push({ type: i[0], id: i[1], num: i[2], eff: e }) } } onSigninSuc() { this.signinData = gameData().activity.getSigninDataById(this.signinId), this.refreshUI() } async refreshUI() {
                for (let i = 0; i < this.dbRewards.length; i++) {
                    let t = this.Find("" + (i + 1), this.list), e = (0, c.Ay)(`label.time.day${i + 1}`, "label.time.day1"); this.GetComponent("bg/text", n.TMPro.TextMeshProUGUI, t.transform).text = e; let s = this.Find("bg/done", t.transform), a = this.hasSignined(i + 1); s.gameObject.SetActive(a)
                        ; let o = this.Find("bg/finish", t.transform), r = this.canSignin(i + 1); o.gameObject.SetActive(!1), this.buttonOn("bg", (() => { this.onClickDay(i + 1, r) }), t.transform); let d = this.dbRewards[i], h = this.Find("bg/reward", t.transform); await this.setReward(h, d)
                }
            } async setReward(i, t) { if (t.type == f.uN4.PROP_KIND_ITEM) { let e = this.Find("icon/itemIcon", i); e && await this.setItemIcon(e, t.id, t.num, !1, t.eff) } else if (t.type == f.uN4.PROP_KIND_REWARD_BOX) { let e = gameData().storage.getRewardBoxItems(t.id), n = (0, o.e8)(i, "icon", e.length); for (let i = 0; i < e.length; i++) { let s = n[i], a = e[i], o = this.Find("itemIcon", s.transform); a.kind == f.uN4.PROP_KIND_ITEM ? await this.setItemIcon(o, a.id, a.num, !1, t.eff) : a.kind == f.uN4.PROP_KIND_EQUIP || a.kind == f.uN4.PROP_KIND_ACTIVITYEQUIP ? await this.setEquipIcon(o, a.id, a.num, t.eff, a.kind) : console.error("首充签到 宝箱奖励包含暂未支持的奖励类型，rewardBoxId = " + t.id) } } else if (t.type == f.uN4.PROP_KIND_EQUIP || t.type == f.uN4.PROP_KIND_ACTIVITYEQUIP) { let e = this.Find("icon/itemIcon", i); await this.setEquipIcon(e, t.id, t.num, t.eff, t.type) } else console.error("首充签到 暂未支持的奖励类型，reward = " + JSON.stringify(t)) } async setItemIcon(i, t, e, n, s) { let a = this.attachPanel(i, u.ItemIconNode), o = f.uN4.PROP_KIND_ITEM; n ? (o = f.uN4.PROP_KIND_REWARD_BOX, await a.initRewardBox(t)) : await a.initItemInfoByIdNum(t, e), a.setEffLevel(s), a.setClickFunc((() => { this.emit("show_simple_propinfo", { kind: o, id: t, num: e, global: this.isBelongToGlobal(), fromPanel: "FirstBuyPanel" }) })) } async setEquipIcon(i, t, e, n, s) { let a = this.attachPanel(i, u.ItemIconNode), o = h.rq.newVirtualEquip(t, e, s); await a.initEquipInfo(o), a.setEffLevel(n), a.setClickFunc((() => { let i = { from: I.EquipInfoFromType.SIMPLE_INFO, id: t, equipData: o }; this.showPanel(UI.EquipInfoBox, i) })) } canSignin(i) { if (this.signinData.signinData.todaySigned) return !1; if (!this.hasSignined(i)) { if (1 == i) return !0; if (this.hasSignined(i - 1)) return !0 } return !1 } hasSignined(i) { return (0, o.B$)(this.signinData.signinData.bits, i) } onClickDay(i, t) {
                if (this.hasSignined(i) || this.signinData.signinData.todaySigned) this.emit("show_one_tip", (0,
                    c.Ay)("notice.activity.signin.signinret5")); else if (t) { let i = { id: this.signinId }; d.SocketManager.instance.sendMsg(g.lZ.Activity_do_signin, i, f.xk1) }
            }
        } __decorate([component("bg/list"), __metadata("design:type", n.UnityEngine.Transform)], SigninPanel1.prototype, "list", void 0)
    }
};